Repository influxdata/platform, pull requests merged in 2018-11, with the labels that each got.

#1266 open tracing context handling for tasks and for HTTP endpoints for tasks and query
  cmd/influxd/main.go
  http/query_service.go
Labels: area/api, area/tasks

#1285 Update flux dependency with distinct push down support
  go.mod
  go.sum
Labels: area/query

#1350 fix to transpiler result encoder when there's no _time column
  query/influxql/result.go
  query/influxql/result_test.go
Labels: bug

#1352 Add display options ui for line graph types
  ui/src/dashboards/constants/cellEditor.ts
  ui/src/shared/actions/v2/timeMachines.ts
  ui/src/shared/components/ColorScaleDropdown.tsx
  ui/src/shared/components/TimeMachineBottom.tsx
  ui/src/shared/components/view_options/LineOptions.tsx
  ui/src/shared/components/view_options/OptionsSwitcher.tsx
  ui/src/shared/components/view_options/ViewOptions.tsx
  ui/src/shared/components/view_options/options/ColorSelector.tsx
  ui/src/shared/components/view_options/options/DecimalPlaces.tsx
  ui/src/shared/components/view_options/options/YAxisAffixes.tsx
  ui/src/shared/components/view_options/options/YAxisBase.tsx
  ui/src/shared/components/view_options/options/YAxisBound.tsx
  ui/src/shared/components/view_options/options/YAxisBounds.tsx
  ui/src/shared/components/view_options/options/YAxisScale.tsx
  ui/src/shared/components/view_options/options/YAxisTitle.tsx
  ui/src/shared/reducers/v2/timeMachines.ts
Labels: area/chronograf

#1329 fix(tsdb): eliminate data race from *SeriesIDSet.Clone
  tsdb/series_set.go
  tsdb/series_set_test.go
Labels: area/storage/tsi, data race

#1363 Feat/transpiler show databases
  query/functions/inputs/buckets.go
  query/functions/inputs/databases.go
  query/influxql/spectests/show_databases.go
  query/influxql/transpiler.go
Labels: enhancement

#1398 Fix encoding bug that could tie up compactions
  pkg/encoding/simple8b/encoding.go
  pkg/encoding/simple8b/encoding_test.go
  tsdb/tsm1/compact.gen.go
  tsdb/tsm1/compact.gen.go.tmpl
  tsdb/tsm1/compact_test.go
Labels: area/storage

#1345 reduce parsing and copying of tags
  tsdb/explode.go
Labels: area/performance

#1564 add run return to rerun
  cmd/influx/task.go
  http/swagger.yml
  http/task_service.go
  mock/task_service.go
  task.go
  task/backend/bolt/bolt.go
  task/backend/inmem_logreaderwriter.go
  task/backend/inmem_store.go
  task/backend/meta.go
  task/backend/meta.pb.go
  task/backend/meta.proto
  task/backend/meta_test.go
  task/backend/store.go
  task/backend/storetest/storetest.go
  task/platform_adapter.go
  task/servicetest/servicetest.go
Labels: area/tasks

#1265 Add scanned value & bytes statistics.
  cmd/influxd/main_test.go
  go.mod
  go.sum
  http/query_service.go
  http/task_service.go
  query/bridges.go
  query/functions/inputs/storage/storage.go
  query/influxql/response_iterator.go
  query/promql/promql.go
  storage/reads/array_cursor.gen.go
  storage/reads/array_cursor.gen.go.tmpl
  storage/reads/datatypes/storage_common.pb.go
  storage/reads/group_resultset.go
  storage/reads/merge.go
  storage/reads/reader.go
  storage/reads/resultset.go
  storage/reads/store.go
  storage/reads/stream_reader.gen.go
  storage/reads/stream_reader.gen.go.tmpl
  storage/reads/stream_reader.go
  storage/reads/table.gen.go
  storage/reads/table.gen.go.tmpl
  storage/reads/table.go
  task/backend/executor/executor_test.go
  task/servicetest/servicetest.go
  tsdb/cursors/cursor.go
  tsdb/internal/meta.pb.go
  tsdb/tsm1/array_cursor.gen.go
  tsdb/tsm1/array_cursor.gen.go.tmpl
  tsdb/tsm1/array_cursor_iterator.go
  tsdb/tsm1/iterator.gen.go.tmpldata
Labels: area/storage
